### ISSUE TITLE
Create a test to validate link creation

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1375] opened 2023-03-26 19:59 UTC
See #167 

Use Scrapy to crawl a wiki and report broken links. Define how wiki admins will start the process and view the results.

**Comment by bylsmad** [comment] 2023-03-28 13:59
@RogerHaase thanks for your time responding to the previous pull request here are my responses:

### purpose/location of the test

in your suggestion to move the test into loadtesting or similar, I think you've mistaken the purpose of the test.

the scrapy test is meant to be a functional test, not an end user admin utility.  my apologies for not being clearer on the purpose of this code, here it is:

goal: insure all converters create expected links including when moin is running behind webserver not at server root

requirements:

* test should run as part of github "test with pytest" action step
  NOTE: for pull request, the test must pass, use xfail if there are unresolved issues which the test identifies
* should be able to run the test with minimal modification so it will target a remote instance of moin running behind webserver with a wiki_root
* the test should check for proper values of href, src, data and data-href attributes on all elements with complete code coverage for code which produces them
* the test should create then clean up wiki index and storage which is used in the test for ease of repeatability

would it be possible to rename this issue to "create a test to validate link production"

### location of test artifacts

As I was working on getting the test to pass under the github action, I found it useful to archive crawl.log crawl.csv and server.log.  As I create more functional tests, I'm expecting there to be more files of this type, would it make sense to create a _test_artifacts folder?  perhaps sibling of src directory?  that would make the archive action simpler in ci.yml

### server startup in the test

Could you let me know a bit more about the SyntaxError you saw in the server.log?  The server startup should be happening automatically when you run the test under pytest

I'm thinking maybe the issue is that src/moin/_tests/sitetesting/wikiconfig.py is a symlink perhaps in your clone the symlink is not getting created properly?  I've pushed change which has copy of the file instead of symlink, could you pull down current and try:

`pytest src/moin/_tests/sitetesting/test_scrapy_crawl.py`

### Discussion links

I have the Discussion links as expected either 404 or 200 in the test currently, and given that the test runs with a static wikiconfig.py, I'm not seeing need to dynamically find this string from 'supplementation_item_names' setting.

### rebase

I've rebased and squashed the commits in current 167-scrapy-test branch, will do this once more before next pull req.

### help-test idea

As I worked on #1373  I started thinking a more direct way of writing this test would be to create a help-test in the sitetesting folder which has one page each for the different content types each of which produces nearly same html output, then I could make a test which does `moin load-test -n test` and GETs each page and makes assertions to validate presence of the expected content.  Could be a nice framework for testing all kinds of elements across the content types.  what do you think?  

### related effort

I've also been working on reviving the selenium tests under _ui_tests it is in https://github.com/moinwiki/moin/commit/590719ea91571871f266f28fa80f33336b78372f.  This branch takes off from the 167-scrapy-test, so need to get this bit merged before posting that piece.  I'm a bit worried about being sure to keep on the good side of the licensing issues with selenium, particularly when the tests run under the github action.  If you have time to take a look at that commit in mean time that would be great.

**Comment by bylsmad** [comment] 2023-03-29 04:26
@RogerHaase  the 404 for /help-en is a new error I'm seeing it in all environments ever since I rebased to master

it is looking to me that the upgrade to Werkzeug 2.2.3 is possibly cause?

```
git checkout 997d1be5d9c3355cfa99643d4eb51223827230fe
rm -rf ../moin-venv-python3
./quickinstall.py
. ./activate 
moin run
# /help-en/Home loads OK
exit
# new session
git checkout d9303b25a71b23bf2030c28c666742266abc17dd
rm -rf ../moin-venv-python3
./quickinstall.py
. ./activate 
moin run
# 404 error for /help-en/Home
```

**Comment by bylsmad** [comment] 2023-03-30 00:29
I've filed the 404 issue as #1376 found a fix, pull req coming soon

**Comment by RogerHaase** [comment] 2023-03-30 15:47
I have seen the `server overload or corrupt index` error on Windows 10 while running the Locust stress tests with a large number of concurrent requests. I have never seen the problem on Ubuntu and it only happens sometimes on Windows using the built-in server.

If you have a way to slow the interval between crawler requests that will likely avoid the problem.

iirc the net result is the item is written but the item's index is not written. An index rebuild is required to correct the index. 

There should probably be some documentation on how a wiki admin can recognize the problem (view the log everyday?) and correct the problem.

**Comment by UlrichB22** [comment] 2023-04-10 21:12
> one question: in server.log I'm seeing intermittent errors like the below. does this represent a bug? is there a workaround?
> 
> ```
> 2023-03-30 05:37:44,365 ERROR moin.apps.feed.views:87 content rendering crashed
> Traceback (most recent call last):
>   File "/home/bylsmad/PycharmProjects/moin/src/moin/apps/feed/views.py", line 79, in atom
>     previous_rev = item[previous_revid]
>   File "/home/bylsmad/PycharmProjects/moin/src/moin/storage/middleware/protecting.py", line 398, in __getitem__
>     rev = self.item[revid]
>   File "/home/bylsmad/PycharmProjects/moin/src/moin/storage/middleware/indexing.py", line 1125, in __getitem__
>     return Revision(self, revid)
>   File "/home/bylsmad/PycharmProjects/moin/src/moin/storage/middleware/indexing.py", line 1283, in __init__
>     doc = get_indexer(item.indexer._document, idx_name=ALL_REVS, revid=revid)
>   File "/home/bylsmad/PycharmProjects/moin/src/moin/storage/middleware/indexing.py", line 120, in get_indexer
>     raise KeyError(kw.get('revid', '') + ' - server overload or corrupt index')
> KeyError: 'a29ae97b056f4ce1b5571e13fc34d338 - server overload or corrupt index'
> ```

Can reproduce this error on debian when trying to access http://localhost:5000/+feed/atom on a newly create wiki using `moin create-instance --full`. Loading takes a long time and there are 6 tracebacks with `overload or corrupt index`. 

`apps/feed/view.py` doesn't handle namespaces yet. When using debug logging you will see e.g. 
`DEBUG moin.items:318 No such item: CompositeName(namespace='', field='name_exact', value='WikiDict')`
Namespace should be help-en.

**Comment by RogerHaase** [comment] 2023-04-11 20:25
Similar results on Windows 10, but only 5 tracebacks: probably different wiki content.

The problem is invalid help-en meta data. Several items have invalid parentid fields. StronaGłówna, MoinWikiMacros, mediawiki, html, and docbook.

Will open new issue.

**Closed** 2023-04-23 19:55 UTC
Labels: enhancement
