### ISSUE TITLE
Install fails with "struct.error: unpack requires a buffer of 44 bytes"

### ISSUE THREAD

**Issue by socketbox** [moinwiki/moin#1544] opened 2023-10-07 01:38 UTC
I've tried running `python ./quickinstall.py` using various versions of the standard interpreter (`3.8.18`, `3.10.13`, and `3.11.5`) and each time it failed. Here's an excerpt from `m-quickisntall.txt` (I've attached the full file).

```
  dist.fetch_build_eggs(dist.setup_requires)
WARNING: The wheel package is not available.
WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
Traceback (most recent call last):
  File "/opt/moinmoin2/mm2/setup.py", line 137, in <module>
    setup(**setup_args)
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/setuptools/dist.py", line 303, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/setuptools/dist.py", line 680, in finalize_options
    ep(self)
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/setuptools/dist.py", line 700, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
    ^^^^^^^^^
  File "/home/chb/.asdf/installs/python/3.11.5/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chb/.asdf/installs/python/3.11.5/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/messages/__init__.py", line 11, in <module>
    from babel.messages.catalog import (
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/messages/catalog.py", line 24, in <module>
    from babel.dates import format_datetime
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/dates.py", line 34, in <module>
    from babel import localtime
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/__init__.py", line 41, in <module>
    LOCALTZ = get_localzone()
              ^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/__init__.py", line 37, in get_localzone
    return _get_localzone()
           ^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/_unix.py", line 36, in _get_localzone
    return _tz_from_env(tzenv)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/_unix.py", line 18, in _tz_from_env
    return _get_tzinfo_from_file(tzenv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/_helpers.py", line 41, in _get_tzinfo_from_file
    return pytz.tzfile.build_tzinfo('local', tzfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/pytz/tzfile.py", line 28, in build_tzinfo
    typecnt, charcnt) = unpack(head_fmt, fp.read(head_size))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 44 bytes
Traceback (most recent call last):
  File "/opt/moinmoin2/mm2/quickinstall.py", line 728, in <module>
    QuickInstall(os.path.dirname(os.path.realpath(args[0])))()
  File "/opt/moinmoin2/mm2/quickinstall.py", line 564, in __call__
    self.do_catalog()
  File "/opt/moinmoin2/mm2/quickinstall.py", line 596, in do_catalog
    subprocess.check_call((
  File "/home/chb/.asdf/installs/python/3.11.5/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/opt/moinmoin2/mm2-venv-python/bin/python', '/opt/moinmoin2/mm2/setup.py', 'compile_catalog', '--statistics', '--dire
ctory', '/opt/moinmoin2/mm2/src/moin/translations')' returned non-zero exit status 1.
```
[m-quickinstall.txt](https://github.com/moinwiki/moin/files/12836274/m-quickinstall.txt)

**Comment by UlrichB22** [comment] 2023-10-07 07:43
Thanks for trying moin2.
Please have a look at https://github.com/polybar/polybar/issues/1930 .
Seems to be an issue with timezone setup.

**Comment by ThomasWaldmann** [comment] 2023-10-07 10:45
`pytz` tries to read a tzinfo file (should start with `TZif`) and likely does a short read instead of the expected 44 bytes it wanted to read - could be a truncated, maybe a 0 bytes length file.

What's in your `TZ` environment variable at that time?

Does it point to a file? `ls -l <that_file>`

**Comment by RogerHaase** [comment] 2023-10-07 14:18
Are you in Arizona? #1510

**Comment by socketbox** [comment] 2023-10-08 06:30
Hi, thanks for the prompt response. Here's some shell output:
```
[2023-10-06 21:24:02]» echo $TZ
:/etc/timezone
[2023-10-08 02:23:54]» cat /etc/timezone 
───────┬─────────────────────────────────────
       │ File: /etc/timezone
───────┼─────────────────────────────────────
   1   │ America/New_York
───────┴─────────────────────────────────────
[2023-10-08 02:26:35]» ls -al /etc/timezone
-rw-r--r-- 1 root root 17 Jun  1 13:12 /etc/timezone
[2023-10-08 02:27:23]» ls -al /etc/localtime 
lrwxrwxrwx 1 root root 36 Jun  1 13:12 /etc/localtime -> /usr/share/zoneinfo/America/New_York
[2023-10-08 02:29:02]» file /usr/share/zoneinfo/America/New_York
/usr/share/zoneinfo/America/New_York: timezone data (fat), version 2, 6 gmt time flags, 6 std time flags, no leap seconds, 236 transition times, 6 local time types, 20 abbreviation chars
```

**Comment by UlrichB22** [comment] 2023-10-08 09:19
I could reproduce the problem after setting `export TZ=":/etc/timezone"`
It is a valid setting according to https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
but i have never seen it before. Usually TZ should not be needed.

Can you please try to run `unset TZ` before running quickinstall?

**Comment by ThomasWaldmann** [comment] 2023-10-08 19:05
If the file does not start with the magic `TZif` string, it is not what the code expects it to be.

**Comment by socketbox** [comment] 2023-10-12 01:42
Unsetting `TZ` worked. Thanks.

While procrastinating, I decided to look further into this problem.  Simply importing `babel.dates` causes an error:

```
[2023-10-11 21:23:29]» python
Python 3.11.2 (main, Feb 21 2023, 21:44:41) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel.dates
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/dates.py", line 34, in <module>
    from babel import localtime
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/__init__.py", line 41, in <module>
    LOCALTZ = get_localzone()
              ^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/__init__.py", line 37, in get_localzone
    return _get_localzone()
           ^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/_unix.py", line 36, in _get_localzone
    return _tz_from_env(tzenv)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/_unix.py", line 18, in _tz_from_env
    return _get_tzinfo_from_file(tzenv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/babel/localtime/_helpers.py", line 41, in _get_tzinfo_from_file
    return pytz.tzfile.build_tzinfo('local', tzfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/moinmoin2/mm2-venv-python/lib/python3.11/site-packages/pytz/tzfile.py", line 28, in build_tzinfo
    typecnt, charcnt) = unpack(head_fmt, fp.read(head_size))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 44 bytes
```
Babel apparently relies on pytz and [pytz itself states](https://pypi.org/project/pytz/): 
>This project is in maintenance mode. Projects using Python 3.9 or later are best served by using the timezone functionaly (sic) now included in core Python [edit: presumably `zoneinfo`] and packages that work with it such as [tzdata](https://pypi.org/project/tzdata/).

**Comment by ThomasWaldmann** [comment] 2023-10-12 13:29
@socketbox Doesn't look like a python version related issue though. That code obviously expects the file content pointed to via TZ to be something different.

**Comment by UlrichB22** [comment] 2023-10-12 18:47
@socketbox thanks for the clarification. We only have 2 lines of code that use pytz and will eventually switch to zoneinfo. 
Can we close this issue since it has nothing to do with our code?

**Closed** 2023-10-14 21:14 UTC
