### ISSUE TITLE
How to install with nginx and systemd?

### ISSUE THREAD

**Issue by alexxroche** [moinwiki/moin#1758] opened 2024-09-11 14:25 UTC
I used to have moin 1.9.11 installed and thought that I would upgrade. I've tried but failed and thought that I'd report what I have tried and how far I got so that others can wait for a working install_moin2.py script rather than ending up in the same wilderness as I did.

1. I went to https://moin-20.readthedocs.io/en/latest/admin/install.html#installing-the-code and followed the instructions
```bash
mkdir /var/www/moin
cd !$
python3 -m venv .venv
. .venv/bin/activate
pip install --upgrade pip
pip install --pre moin
# check moin2 is installed
moin --help 2>&1 1>/dev/null && echo "ok" || echo "[e] install moin2";

```

2.  created instance with `moin create-instance --path /var/www/moin`
3. edited wikiconfig.py
```txt
* sitename - name of your wiki
* interwikiname - wtf ? I don't want to be linked to other wikis
* acls - SuperUser and SuperEditor - do I have to edit this to get a minimum viable wiki running?
* registration only by superuser - this is a good default
* edit locking policy - I only have a few users so the default seems ok for now
* email configuration - remember to put the email address in quotes
* namespaces and backends - I'll come back to this when I've read more
* SECRET_KEY - filled with $(uuidgen) x4
```                                            
4. generated the index `moin index-create` (should have waited until after the import from 1.9 ! )
5.  created `/etc/systemd/system/moin.service`

```service
[Unit]
Description = moin_wiki
After = network.target

[Service]
Type=simple
Restart=always
#Environment="PATH=/var/www/moin/venv/bin:$PATH"
PermissionsStartOnly = true
PIDFile = /run/moin/moin.pid
User = nginx
Group = nginx
WorkingDirectory = /var/www/moin
ExecStartPre = /bin/mkdir -p /run/moin /var/www/moin/log
ExecStartPre = /bin/chown -R nginx: /run/moin /var/www/moin/log
ExecStart = /var/www/moin/.venv/bin/python /var/www/moin/.venv/bin/moin run --port 8081 --no-debugger --no-reload

ExecReload = /bin/kill -s HUP $MAINPID
ExecStop = /bin/kill -s TERM $MAINPID
ExecStopPost = /bin/rm -rf /run/moin
PrivateTmp = true

[Install]
WantedBy = multi-user.target
```
6. create an nginx config `/etc/nginx/sites-available/moin`
`sudo mkdir -p /etc/nginx/sites-available; sudo mkdir -p /etc/nginx/sites-enabled`

```nginx
server {
	listen 80;
	listen [::]:80;

	server_name www.example.com example.com localhost wiki.lan;
	index index.html index.htm index.nginx-debian.html;

    location / {
        # redirect any requests to the same URL but on https
        return 301 https://$host$request_uri;
    }
}

server {
	# SSL configuration
	
	 listen 443 ssl;
	 listen [::]:443 ssl;
	 include snippets/snakeoil.conf;
	
	root /var/www/moin/html;

	#
	index index.html;

	server_name www.example.com example.com localhost wiki.lan;

    access_log /var/www/moin/log/access.log;
    error_log  /var/www/moin/log/error.log;

    location = /favicon.ico { access_log off; log_not_found off; }
 
	location / {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
     }
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	location ~ /\.ht {
		deny all;
	}

    #if ($uri ~ ^/wiki(.*)?) {
    #    set $wiki_url $1;
    #}

    location /+serve/pygments/css {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/xstatic/pkg/pygments/data/css;
    }
    location /+serve/font_awesome/css {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/xstatic/pkg/font_awesome/data/css;
    }
    location /_themes/topside/css {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/moin/themes/topside/static/css;
    }
    location /+serve/jquery {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/xstatic/pkg/jquery/data;
    }
    # yes I know this is going down the wrong track but it throws fewer errors in the browser like this
    location /+serve/autosize {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/xstatic/pkg/autosize/data;
    }
    location /+template {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/moin/templates;
    }
    location /+serve/jquery_tablesorter {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/xstatic/pkg/jquery_tablesorter/data;
    }
    location /+serve/font_awesome/webfonts {
        alias /var/www/moin/.venv/lib/python3.9/site-packages/xstatic/pkg/font_awesome/data/webfonts;
    }
    #location /static {
    #    alias /var/www/moin/.venv/lib/python3.9/site-packages/moin/static;
    #}
    #location ~ ^/moin_static[0-9]+/(.*) {
    #    alias /var/www/1911moin/MoinMoin/web/static/htdocs/$1;
    #}

    location /favicon.ico {
        #alias /var/www/1911moin/MoinMoin/web/static/htdocs/favicon.ico;
        alias /var/www/moin/.venv/lib/python3.9/site-packages/moin/static/logos/favicon.ico;
    }

    #location /wiki {
    #    proxy_pass       http://127.0.0.1:8081;
    #    proxy_set_header Host      $host;
    #    proxy_set_header X-Real-IP $remote_addr;
    #}

    location /wiki {
        try_files           $uri @wiki_home_rewrite;        
    }
    # location /RecentChanges /FindPage /HelpContents
    # location /BadContent /MissingPage /LanguageSetup
    # location /FrontPage
    location ~ ^/[A-Z]+[a-z0-9]*([A-Z]*[a-z]*)* {
        try_files           $uri $uri/index.html @wiki_home_rewrite;        
    }
    location ~ ^/+serve/([a-z_]*[/]*)* {
        try_files           $uri $uri/index.html @wiki_home_rewrite;        
    }
    location ~ ^/static/([a-z_\.]*[/]*)* {
        try_files           $uri $uri/index.html @wiki_home_rewrite;        
    }
    location @wiki_home_rewrite {
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    Host $http_host;
        proxy_set_header    SCRIPT_NAME /wiki;
        #proxy_set_header    SCRIPT_NAME /;
        proxy_redirect      off;
        proxy_pass          http://127.0.0.1:8081;
    }

    ### enable cgi ###
    # fcgiwrap - probably don't need this at all for moin2
    location /cgi/ { 
      # Disable gzip (it makes scripts feel slower since they have to complete
      # before getting gzipped)
      gzip off;

      # Set the root to /usr/lib (inside this location this means that we are
      # giving access to the files under /usr/lib/cgi-bin)
      root	/var/www/moin/cgi;

      # Fastcgi socket
      fastcgi_pass  unix:/var/run/fcgiwrap.socket;

      # Fastcgi parameters, include the standard ones
      include /etc/nginx/fastcgi_params;

      # Adjust non standard parameters (SCRIPT_FILENAME)
      fastcgi_param SCRIPT_FILENAME  /var/www/moin$fastcgi_script_name;
    }
}

```
8. create /Home with `moin welcome`  I should have skipped this
9. import from my old moin 1.9.11 `moin import19 /var/www/1911moin/wiki/data/`
10. `sudo systemctl daemon-reload; systemctl start moin;`
11. Just for testing `echo "127.0.0.1 wiki.lan" >> /etc/hosts`
12. `cd /etc/nginx/sites-enabled/ && ln -s /etc/nginx/sites-available/moin moin`
13. `sudo nginx -t && sudo systemctl restart nginx`
14. check it works `curl -sL  'https://wiki.lan/Home'` 
   Which gives me a nice page
15. `curl -sL 'https://wiki.lan/+login'` gives me "404 Not Found"

After a few days of trying to tweak many settings this is as far as I've managed with Moin2 and the installed wiki is unusable. I even tried running it behind gunicorn, (which I currently use for other projects) but that didn't fix the `/+login` not working.)

I just really **really** don't want to have to install PHP just to install [DokuWiki](https://www.dokuwiki.org/) even though DokuWiki seems to "just work".

**Comment by UlrichB22** [comment] 2024-09-11 20:03
@alexxroche: thanks for testing moin 2.0. 

To check, if the problem is related to moin or the nginx configuration you can try to start the built-in server with `
'moin run'` and run your curl commands against it without nginx.

I am not an nginx expert, but can you check your configured rules? I don't see any rule that applies to '+login'.
 
AFAIK the usual nginx setup is using uwsgi. Maybe someone can help and provide a short guide on how to set up nginx with uwsgi.

**Comment by UlrichB22** [comment] 2024-09-28 20:14
@alexxroche, can we close this issue?

**Comment by UlrichB22** [comment] 2024-10-22 16:46
The ticket is closed because there is no feedback. It can be reopened if required.

**Closed by UlrichB22** 2024-10-22 16:46 UTC
