### ISSUE TITLE
During new page creation in Windows - Internal Server Error

### ISSUE THREAD

**Issue by msh707** [moinwiki/moin#740] opened 2018-10-28 12:46 UTC
Steps to reproduce:
1) Create a new page
2) Select MoinMoin under "Markup Text Items"
3) Select Template Sample
4) Click on Ok

= > Internal Server Error is shown
But the page has been created

Please note: this war the try to create a page after local environment set-up on windows 10

**Comment by RogerHaase** [comment] 2018-10-28 13:18
Cannot reproduce, please post the traceback in the server log.

**Comment by msh707** [comment] 2018-10-28 13:52
----------------------------------------
2018-10-28 13:39:52,030 INFO moin.utils.clock:45 timer init(0): 5.00ms
2018-10-28 13:39:52,102 INFO moin.utils.clock:45 timer navibar(0): 0.00ms
2018-10-28 13:39:52,125 INFO moin.utils.clock:45 timer total(0): 99.00ms
2018-10-28 13:39:52,125 INFO werkzeug:88 127.0.0.1 "POST /+modify/Home/neu123?contenttype=text%2Fx.moin.wiki%3Bcharset%3Dutf-8&itemtype=default&template=TemplateSample HTTP/1.1" 200 -
2018-10-28 13:39:52,164 INFO werkzeug:88 127.0.0.1 "GET /static/img/admonitions/warning.png HTTP/1.1" 200 -
2018-10-28 13:39:52,278 INFO werkzeug:88 127.0.0.1 "GET /static/img/smileys/icon-error.png HTTP/1.1" 200 -
2018-10-28 13:40:01,048 INFO moin.utils.clock:45 timer init(0): 2.00ms
2018-10-28 13:40:01,048 INFO moin.signalling.log:19 item MyMoinMoin:Home/neu123 displayed
2018-10-28 13:40:01,062 INFO moin.utils.clock:45 timer conv_in_dom(0): 4.00ms
2018-10-28 13:40:01,062 INFO moin.utils.clock:45 timer nowiki(0): 0.00ms
2018-10-28 13:40:01,063 INFO moin.utils.clock:45 timer conv_include(0): 1.00ms
2018-10-28 13:40:01,065 INFO moin.utils.clock:45 timer conv_macro(0): 0.00ms
2018-10-28 13:40:01,065 INFO moin.utils.clock:45 timer conv_link(0): 0.00ms
2018-10-28 13:40:01,071 INFO moin.utils.clock:45 timer conv_dom_html(0): 4.00ms
2018-10-28 13:40:01,118 INFO moin.utils.clock:45 timer navibar(0): 1.00ms
2018-10-28 13:40:01,137 INFO moin.utils.clock:45 timer total(0): 91.00ms
2018-10-28 13:40:01,138 INFO werkzeug:88 127.0.0.1 "GET /Home/neu123 HTTP/1.1" 200 -
2018-10-28 13:43:32,895 INFO moin.utils.clock:45 timer init(0): 3.00ms
2018-10-28 13:43:32,898 INFO moin.signalling.log:19 item MyMoinMoin:Home/neu1234 displayed
2018-10-28 13:43:32,956 INFO moin.utils.clock:45 timer navibar(0): 1.00ms
2018-10-28 13:43:32,983 INFO moin.utils.clock:45 timer total(0): 90.00ms
2018-10-28 13:43:32,983 INFO werkzeug:88 127.0.0.1 "GET /Home/neu1234 HTTP/1.1" 404 -
2018-10-28 13:43:37,063 INFO moin.utils.clock:45 timer init(0): 1.00ms
2018-10-28 13:43:37,125 INFO moin.utils.clock:45 timer navibar(0): 1.00ms
2018-10-28 13:43:37,147 INFO moin.utils.clock:45 timer total(0): 84.00ms
2018-10-28 13:43:37,148 INFO werkzeug:88 127.0.0.1 "GET /+modify/Home/neu1234?contenttype=text%2Fx.moin.wiki%3Bcharset%3Dutf-8&itemtype=default HTTP/1.1" 200 -
2018-10-28 13:43:41,723 INFO moin.utils.clock:45 timer init(0): 2.00ms
2018-10-28 13:43:41,723 INFO moin.signalling.log:19 item MyMoinMoin:Home/neu1234 displayed
2018-10-28 13:43:41,782 INFO moin.utils.clock:45 timer navibar(0): 0.00ms
2018-10-28 13:43:41,811 INFO moin.utils.clock:45 timer total(0): 90.00ms
2018-10-28 13:43:41,811 INFO werkzeug:88 127.0.0.1 "GET /Home/neu1234 HTTP/1.1" 404 -
2018-10-28 13:44:54,101 INFO moin.utils.clock:45 timer init(0): 1.00ms
2018-10-28 13:44:54,167 INFO moin.utils.clock:45 timer navibar(0): 1.00ms
2018-10-28 13:44:54,188 INFO moin.utils.clock:45 timer total(0): 88.00ms
2018-10-28 13:44:54,188 INFO werkzeug:88 127.0.0.1 "GET /+modify/Home/neu1234?contenttype=text%2Fx.moin.wiki%3Bcharset%3Dutf-8&itemtype=default HTTP/1.1" 200 -
2018-10-28 13:44:56,618 INFO moin.utils.clock:45 timer init(0): 1.00ms
2018-10-28 13:44:56,676 INFO moin.utils.clock:45 timer navibar(0): 1.00ms
2018-10-28 13:44:56,700 INFO moin.utils.clock:45 timer total(0): 82.00ms
2018-10-28 13:44:56,700 INFO werkzeug:88 127.0.0.1 "GET /+modify/Home/neu1234?contenttype=text%2Fx.moin.wiki%3Bcharset%3Dutf-8&itemtype=default&template=TemplateSample HTTP/1.1" 200 -
2018-10-28 13:45:22,538 INFO moin.utils.clock:45 timer init(0): 1.00ms
2018-10-28 13:45:22,697 INFO moin.signalling.log:25 item MyMoinMoin:Home/neu1234 modified
2018-10-28 13:45:22,716 INFO moin.utils.clock:45 timer total(0): 180.00ms
2018-10-28 13:45:22,716 INFO werkzeug:88 127.0.0.1 "POST /+modify/Home/neu1234?contenttype=text%2Fx.moin.wiki%3Bcharset%3Dutf-8&itemtype=default&template=TemplateSample HTTP/1.1" 302 -
2018-10-28 13:45:22,720 INFO moin.utils.clock:45 timer init(0): 0.00ms
2018-10-28 13:45:22,721 INFO moin.signalling.log:19 item MyMoinMoin:Home/neu1234 displayed
2018-10-28 13:45:22,732 INFO moin.utils.clock:45 timer conv_in_dom(0): 2.00ms
2018-10-28 13:45:22,733 INFO moin.utils.clock:45 timer nowiki(0): 0.00ms
2018-10-28 13:45:22,733 INFO moin.utils.clock:45 timer conv_include(0): 1.00ms
2018-10-28 13:45:22,734 INFO moin.utils.clock:45 timer conv_macro(0): 1.00ms
2018-10-28 13:45:22,736 INFO moin.utils.clock:45 timer conv_link(0): 0.00ms
2018-10-28 13:45:22,739 INFO moin.utils.clock:45 timer conv_dom_html(0): 3.00ms
2018-10-28 13:45:22,792 INFO moin.utils.clock:45 timer navibar(0): 0.00ms
2018-10-28 13:45:22,821 INFO moin.utils.clock:45 timer total(0): 100.00ms
2018-10-28 13:45:22,821 INFO werkzeug:88 127.0.0.1 "GET /Home/neu1234 HTTP/1.1" 200 -
2018-10-28 13:45:30,049 INFO moin.utils.clock:45 timer init(0): 1.00ms
2018-10-28 13:45:30,164 INFO moin.utils.clock:45 timer navibar(0): 0.00ms
2018-10-28 13:45:30,200 INFO moin.utils.clock:45 timer total(0): 153.00ms
2018-10-28 13:45:30,201 INFO werkzeug:88 127.0.0.1 "GET /+modify/Home/neu1234?contenttype=text%2Fx.moin.wiki%3Bcharset%3Dutf-8&itemtype=default&template=TemplateSample HTTP/1.1" 200 -

**Comment by ReimarBauer** [comment] 2018-11-01 09:45
At that time it was just a new installation, it was during the sprint (PyConDE).

**Comment by RogerHaase** [comment] 2020-03-21 15:21
cannot reproduce, closing

**Closed by RogerHaase** 2020-03-21 15:21 UTC
