### ISSUE TITLE
SyntaxError: Non-ASCII character '\x90' in file...\Scripts\moin.exe

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#571] opened 2017-10-23 17:45 UTC
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/571) by RogerHaase (Bitbucket: [RogerHaase](https://bitbucket.org/RogerHaase), GitHub: [RogerHaase](https://github.com/RogerHaase)).**

----------------------------------------

On Windows, sometimes after running "m quickinstall" there is a failure starting the built-in server:

    C:\Bitbucket\moin2>m run
    2017-10-23 09:23:51,296 INFO MoinMoin.log:157 using logging configuration read from built-in fallback in MoinMoin.log mo
    dule!
    2017-10-23 09:23:51,296 INFO MoinMoin.log:162 Running MoinMoin 2.0.0a0 code from c:\bitbucket\moin2\MoinMoin
    2017-10-23 09:23:52,132 INFO MoinMoin.util.clock:45 timer create_app load config(0): 16.00ms
    2017-10-23 09:23:52,167 INFO MoinMoin.util.clock:45 timer create_app register(0): 33.00ms
    2017-10-23 09:23:52,167 WARNING MoinMoin.log:119 c:\bitbucket\moin2-venv-python\lib\site-packages\flask_caching\__init__
    .py:184: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
    2017-10-23 09:23:52,178 INFO MoinMoin.util.clock:45 timer create_app flask-cache(0): 12.00ms
    2017-10-23 09:23:52,229 INFO MoinMoin.util.clock:45 timer create_app init backends(0): 50.00ms
    2017-10-23 09:23:52,229 INFO MoinMoin.util.clock:45 timer create_app flask-babel(0): 0.00ms
    2017-10-23 09:23:52,230 INFO MoinMoin.util.clock:45 timer create_app flask-themes(0): 1.00ms
    2017-10-23 09:23:52,230 INFO MoinMoin.util.clock:45 timer create_app total(0): 114.00ms
    2017-10-23 09:23:52,243 INFO werkzeug:87  * Restarting with stat
      File "C:\Bitbucket\moin2-venv-python\Scripts\moin.exe", line 1
    SyntaxError: Non-ASCII character '\x90' in file C:\Bitbucket\moin2-venv-python\Scripts\moin.exe on line 1, but no encodi
    ng declared; see http://python.org/dev/peps/pep-0263/ for details
    
    C:\Bitbucket\moin2>

The problem goes away by running "m quickinstall" a second time.

**Comment by ThomasWaldmann** [comment] 2018-08-27 16:53
When it happens again, post the contents of `env\Scripts\moin.exe` below (assuming it is basically a text file?).

**Comment by RogerHaase** [comment] 2018-11-05 14:08
moin.exe is a binary executable on windows. 

Have not yet reproduced the problem since migration to GIT. The problem occurred about 5% of the time after running quickinstall when using BitBucket.

**Comment by RogerHaase** [comment] 2020-03-21 15:17
Closing, cannot reproduce, has not happened since git and py3 conversions

**Closed by RogerHaase** 2020-03-21 15:17 UTC
Labels: bug, configuration, os: windows, prio4
